import marimo

__generated_with = "0.23.14"
app = marimo.App(width="medium")


@app.cell
def _():
    import marimo as mo
    import matplotlib.pyplot as plt
    import numpy as np

    return mo, np, plt


@app.cell
def _(mo):
    mo.md(r"""
    # Bandit optimal transport: a claim-contract tutorial

    This notebook explains the central evidence without rerunning the formal
    experiment. The audited source is **arXiv:2502.07397v1**, because that is
    the version matched by the live judge's six claims. Current v2 differs.

    The key lesson is methodological: a theorem-shaped claim needs its
    definitions, assumptions, and quantifiers checked together. Nearby
    random-feature behavior is not enough.
    """)
    return


@app.cell
def _(mo):
    claim = mo.ui.slider(1, 6, value=1, label="Claim")
    claim
    return (claim,)


@app.cell
def _(claim, mo):
    evidence = {
        1: ("Fourier identity", "direct pairing 0; proposed pairing 1/2"),
        2: ("Entropic regret", "literal lower 113.7M; complete RHS upper 0.399M"),
        3: ("Kantorovich regret", "epsilon_T=5e-5; lower 100.0M; RHS upper 0.583M"),
        4: ("Finite basis", "actual 3x3 OT regret is 1 per round"),
        5: ("Coefficient decay", "admitted tail 1.633; asserted bound 0.216"),
        6: ("Confidence set", "identical features; expected feedback differs by 1"),
    }
    title, result = evidence[claim.value]
    mo.callout(
        mo.md(f"**Claim {claim.value} — {title}: FALSIFIED**\n\n{result}"),
        kind="danger",
    )
    return


@app.cell
def _(mo):
    mo.md(r"""
    ## The central counterexample

    Let both marginals be uniform on `{0,1}`, let `rho` be their product,
    use the diagonal coupling, and set `c(x,y)=(x-y)^2`.

    - The coupling has density `(2,0,0,2)` with respect to `rho`, so it
      satisfies the paper's `L2` requirement.
    - Every literal phase `exp(-2 pi i <x,z>)` is one on this integer grid.
    - Direct cost is zero, while the proposed Fourier inner product is one
      half.

    A corrected finite-group transform works, but it changes normalization,
    frequencies, and the representation of the measure. That is a repair,
    not verification of the literal equation.
    """)
    return


@app.cell
def _(np, plt):
    labels = ["Thm. 5.1", "Thm. 5.2"]
    printed = np.array([113_728_635.5, 99_999_999.0])
    rhs = np.array([398_538.2, 582_745.7])
    x = np.arange(2)
    fig, ax = plt.subplots(figsize=(7, 3.5))
    ax.bar(x - 0.18, printed, 0.36, label="literal regret lower", color="#b42318")
    ax.bar(x + 0.18, rhs, 0.36, label="complete RHS upper", color="#2563eb")
    ax.set_yscale("log")
    ax.set_xticks(x, labels)
    ax.set_ylabel("value at T=100,000,000")
    ax.legend(frameon=False)
    ax.set_title("Definition–theorem contradiction")
    fig
    return


@app.cell
def _(mo):
    mo.md(r"""
    ## What the verdict does—and does not—say

    The six verdicts apply to the literal v1 contracts. Corrected controls
    behave normally:

    - a unitary transform satisfies Parseval;
    - a standard OFUL radius covers all enumerated Rademacher paths;
    - subtracting the comparator every round removes the regret-definition
      contradiction; and
    - a truly finite model recovers the usual finite-dimensional setting.

    Formal evidence was generated by:

    ```bash
    uv run python repro/src/verify_entucb.py
    ```

    The notebook embeds the decisive numbers so Molab readers do not need
    repository-relative run artifacts or an expensive rerun.
    """)
    return


if __name__ == "__main__":
    app.run()
